version: '2'

services:
  frontend:
    image: swerpbox/frontend
    # build: ./docker/frontend
    container_name: sb-frontend
    depends_on: rutorrent
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - "./config:/config"
      - "./run/:/run:ro"
    volumes_from:
      - logs_data
      - server_data
    networks:
      - swerpbox

  rutorrent:
    image: swerpbox/rutorrent:1.2.0
    # build: ./docker/rutorrent
    container_name: sb-rutorrent
    restart: always
    ports:
      - "49123:49123"
      - "49123:49123/udp"
      - "6881:6881/udp"
      - "5000:5000"
      - "41812:41812"
    env_file: .env
    volumes:
      - "./config:/config"
      - "./data:/data"
      - "./media:/media"
      - "./run/:/run/:rw"
    links:
      - frontend
    volumes_from:
      - logs_data
      - server_data
    networks:
      - swerpbox

  deluge:
    image: swerpbox/deluge
    # build: ./docker/deluge
    container_name: sb-deluge
    restart: always
    ports:
      - "58946:58946"
      - "58946:58946/udp"
      - "58846:58846"
      - "0.0.0.0:8112:8112"
    env_file: .env
    links:
      - frontend
    volumes:
      - "./config/deluge:/config"
      - "./data:/data"
      - "./media:/media"
    volumes_from:
      - logs_data
    networks:
      - swerpbox

  plex:
     image: plexinc/pms-docker
     container_name: sb-plex
     restart: unless-stopped
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    env_file: .env
    hostname: swerpbox
    networks:
      - swerpbox
    volumes:
      - "./config/plex:/config"
      - "./config/plex/tmp:/transcode"
      - "./media:/data"

  plexpy:
    image: swerpbox/plexpy
    # build: ./docker/plexpy
    container_name: sb-plexpy
    restart: always
    ports:
      - "8181:8181"
    env_file: .env
    volumes:
      - "./config/plex/Library/Application\ Support/Plex\ Media\ Server/Logs/:/logs:ro"
      - "./config/plexpy:/config"
    networks:
      - swerpbox
    depends_on:
      - plex
    links:
      - plex

  # sickrage:
  #   image: swerpbox/sickrage
  #   # build: ./docker/sickrage
  #   container_name: sb-sickrage
  #   ports:
  #     - "8081:8081"
  #   env_file: .env
  #   networks:
  #     - swerpbox
  #   volumes:
  #     - "./config/sickrage:/config"
  #     - "./data:/downloads"
  #     - "./media/TV Shows:/tv"
  #   volumes_from:
  #     - logs_data

  resilio:
    image: swerpbox/resilio-sync
    #build: ./docker/resilio-sync
    container_name: sb-resilio
    ports:
      - "8888:8888"
      - "55555:55555"
    env_file: .env
    networks:
      - swerpbox
    volumes:
      - "./config/resilio:/config"
      - "./data:/data"
    volumes_from:
      - logs_data

  sonarr:
    image: swerpbox/sonarr
    # build: ./docker/sonarr
    container_name: sb-sonarr
    ports:
      - "8989:8989"
    env_file: .env
    networks:
      - swerpbox
    links:
      - frontend
      - rutorrent
    volumes:
      - "./config/sonarr:/config"
      - "./data:/data"
      - "./data/downloading:/downloads"
      - "./media/TV Shows:/tv"
    volumes_from:
      - logs_data

  logs_data:
    image: tianon/true
    volumes:
      - "./logs:/logs"

  server_data:
    image: tianon/true
    volumes:
      - "./srv/nginx:/etc/nginx:ro"
      - "./srv/public:/var/www/public"

networks:
  swerpbox:
    driver: bridge
