version: '2'

services:
  nginx:
    image: swerpbox/nginx
    # build: ./docker/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - rutorrent
    depends_on:
      - rutorrent
    environment:
      PGID: 1000
      PUID: 1000
    volumes:
      - "./web/rutorrent:/web/rutorrent:ro"
      - "./config/nginx/.htpasswd:/etc/nginx/.htpasswd:ro"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./config/nginx/vhost.d:/etc/nginx/vhost.d:ro"
    networks:
      - swerpbox

  rutorrent:
    # image: swerpbox/rutorrent
    build: ./docker/rutorrent
    restart: always
    ports:
      - "49123:49123"
      - "49123:49123/udp"
      - "6881:6881/udp"
    environment:
      PGID: 1000
      PUID: 1000
      TZ: "America/Denver"
    volumes:
      - "./config:/config"
      - "./data:/data"
      - "./media:/media"
      - "./web:/web"
    networks:
      - swerpbox

volumes:
  rutorrent-data:
    driver: local

networks:
  swerpbox:
    driver: bridge
